version: '3.9'

services:
  sake:
    image: zhonger/minihpc:1.0.0
    container_name: sake
    hostname: sake
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezome:ro
      - ./data/share/hosts:/etc/hosts:ro
      - ./data/share/slurm.conf:/etc/slurm/slurm.conf
      - ./data/slurm:/var/spool/slurm
      - ./data/share/slurm-mail.conf:/etc/slurm-mail/slurm-mail.conf
      - ./data/slurm-mail/spool:/var/spool/slurm-mail
      - ./data/share/nslcd.conf:/etc/nslcd.conf
      - ./data/ldap/certs:/usr/local/share/ca-certificates
      - ./data/logs:/opt/logs
      - ./data/root/data:/root/data
      - ./data/users:/home
    # ports:
    #   - "127.0.0.1:10822:22"
      # - "6817:6817"
    environment:
      - ADMIN=true
      - WORKNODE=false
      - LDAP_ENABLE=true
      - SSH_ENABLE=true
    restart: always
    depends_on:
      - db
      - slapd
  w1:
    image: zhonger/minihpc:1.0.0
    container_name: w1
    hostname: w1
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezome:ro
      - ./data/share/hosts:/etc/hosts:ro
      - ./data/share/slurm.conf:/etc/slurm/slurm.conf
      - ./data/share/nslcd.conf:/etc/nslcd.conf
      - ./data/ldap/certs:/usr/local/share/ca-certificates
      - ./data/root/data:/root/data
      - ./data/users:/home
    # ports:
      # - "6818:6818"
    environment:
      - ADMIN=false
      - WORKNODE=true
      - LDAP_ENABLE=true
    restart: always
    depends_on:
      - slapd
  w2:
    image: zhonger/minihpc:1.0.0
    container_name: w2
    hostname: w2
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezome:ro
      - ./data/share/hosts:/etc/hosts:ro
      - ./data/share/slurm.conf:/etc/slurm/slurm.conf
      - ./data/share/nslcd.conf:/etc/nslcd.conf
      - ./data/ldap/certs:/usr/local/share/ca-certificates
      - ./data/root/data:/root/data
      - ./data/users:/home
    # ports:
      # - "6818:6818"
    environment:
      - ADMIN=false
      - WORKNODE=true
      - LDAP_ENABLE=true
    restart: always
    depends_on:
      - slapd
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    hostname: db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezome:ro
      - ./data/share/hosts:/etc/hosts:ro
      - ./data/share/db_init:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=hpc
      - MYSQL_PASSWORD=hpc
    security_opt:
      - seccomp=unconfined
    command: mariadbd --innodb_log_file_size=64M --innodb_lock_wait_timeout=900
  slapd:
    image: osixia/openldap:latest
    container_name: slapd
    restart: always
    hostname: ldap.lisz.top
    environment:
      LDAP_ORGANISATION: "LEP"
      LDAP_DOMAIN: "lisz.top"
      LDAP_ADMIN_PASSWORD: "LEP123456"
      LDAP_READONLY_USER: "True"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly_pass"
      LDAP_TLS_VERIFY_CLIENT: "allow"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezome:ro
      - ./data/share/hosts:/etc/hosts:ro
      - ./data/ldap/db:/var/lib/ldap
      - ./data/ldap/config:/etc/ldap/slapd.d
      - ./data/ldap/certs:/container/service/slapd/assets/certs
    # ports:
    #   - "127.0.0.1:6884:389"
